//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAcessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public EmployeeMaster()
        {
            this.TravelRequests = new HashSet<TravelRequest>();
            this.TravelDetails = new HashSet<TravelDetail>();
        }
    
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Location { get; set; }
        public string ReimbursementAccNo { get; set; }
        public string Designation { get; set; }
        public string UserName { get; set; }
        public byte[] PasswordHASH { get; set; }
    
        public virtual ICollection<TravelRequest> TravelRequests { get; set; }
        public virtual ICollection<TravelDetail> TravelDetails { get; set; }
    }
}
