//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAcessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelDetail
    {
        public TravelDetail()
        {
            this.ExpenseDetails = new HashSet<ExpenseDetail>();
        }
    
        public int MR_Number { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string ReasonForTravel { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public string TravelMode { get; set; }
        public string FromCity { get; set; }
        public string ToCity { get; set; }
        public Nullable<int> TravelDuration { get; set; }
    
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        public virtual ICollection<ExpenseDetail> ExpenseDetails { get; set; }
    }
}
